CREATE DATABASE UNIDAS;
GO

USE UNIDAS;
GO

CREATE TABLE PESSOA(
idPessoa INT PRIMARY KEY IDENTITY (1,1),
nomePessoa varchar(20) NOT NULL UNIQUE 
);
GO 

CREATE TABLE TELEFONE (
idTelefone INT PRIMARY KEY IDENTITY (1,1),
idPessoa INT FOREIGN KEY REFERENCES PESSOA(idPessoa),
numeroTelefone CHAR(11) NOT NULL 
);

CREATE TABLE EMAIL (
idemail INT PRIMARY KEY IDENTITY (1,1),
idTelefone INT FOREIGN KEY REFERENCES PESSOA(idPessoa),
end_email VARCHAR(256) NOT NULL UNIQUE 
);
GO

CREATE TABLE CNH (
idCnh INT PRIMARY KEY IDENTITY (1,1),
idemail INT FOREIGN KEY REFERENCES PESSOA(idPessoa),
descricao VARCHAR(11) NOT NULL UNIQUE 
);
GO

